spring.application.name=social-media-scheduler-api
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.contexts=development
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.web.error.include-stacktrace=never
oauth2.tiktok.client-id=sbawcx12hwik80mokr
oauth2.tiktok.client-secret=4dPS5OPilHPpxsJp48wX89RofpZaaeZo
oauth2.tiktok.scope=user.info.basic,video.publish,video.upload
oauth2.tiktok.redirect-uri=https://unfrugally-erodent-mitchel.ngrok-free.dev/api/login/oauth/code/tiktok
oauth2.tiktok.response-type=code
oauth2.tiktok.grant-type=authorization_code
oauth2.tiktok.authorization-uri=https://www.tiktok.com/v2/auth/authorize
oauth2.tiktok.token-uri=https://open.tiktokapis.com/v2/oauth/token